// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"myproject/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/menu/assign-permissions",
				Handler: AssignMenuPermissionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/menu/create",
				Handler: CreateMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/menu/delete",
				Handler: DeleteMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/menu/get/:id",
				Handler: GetMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/menu/list",
				Handler: ListMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/menu/tree",
				Handler: GetMenuTreeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/menu/update",
				Handler: UpdateMenuHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/product/active-list",
				Handler: ListActiveProductHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/category/create",
				Handler: CreateProductCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/category/delete",
				Handler: DeleteProductCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/product/category/list",
				Handler: ListProductCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/product/category/tree",
				Handler: GetProductCategoryTreeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/category/update",
				Handler: UpdateProductCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/create",
				Handler: CreateProductHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/delete",
				Handler: DeleteProductHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/product/get/:id",
				Handler: GetProductHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/product/list",
				Handler: ListProductHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/unit/create",
				Handler: CreateProductUnitHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/unit/delete",
				Handler: DeleteProductUnitHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/product/unit/get/:id",
				Handler: GetProductUnitHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/product/unit/list",
				Handler: ListProductUnitHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/unit/update",
				Handler: UpdateProductUnitHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/update",
				Handler: UpdateProductHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/warehouse/active-list",
				Handler: ListActiveWarehouseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/warehouse/create",
				Handler: CreateWarehouseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/warehouse/delete",
				Handler: DeleteWarehouseHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/warehouse/get/:id",
				Handler: GetWarehouseHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/warehouse/list",
				Handler: ListWarehouseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/warehouse/update",
				Handler: UpdateWarehouseHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/inventory/adjust",
				Handler: AdjustInventoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inventory/adjust/approve",
				Handler: ApproveInventoryAdjustRequestHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inventory/adjust/create",
				Handler: CreateInventoryAdjustHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/inventory/adjust/list",
				Handler: ListInventoryAdjustHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inventory/adjust/reject",
				Handler: RejectInventoryAdjustRequestHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/inventory/alert/check",
				Handler: CheckInventoryAlertHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/inventory/alert/list",
				Handler: ListInventoryAlertHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inventory/check/create",
				Handler: CreateInventoryCheckHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inventory/check/delete",
				Handler: DeleteInventoryCheckHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/inventory/check/get/:id",
				Handler: GetInventoryCheckHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/inventory/check/list",
				Handler: ListInventoryCheckHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inventory/check/status",
				Handler: UpdateInventoryCheckStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inventory/check/submit",
				Handler: SubmitInventoryCheckHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inventory/check/update",
				Handler: UpdateInventoryCheckHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/inventory/current-stock",
				Handler: GetCurrentStockHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inventory/generate-adjust-from-check",
				Handler: GenerateAdjustFromCheckHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/inventory/get/:id",
				Handler: GetInventoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/inventory/history",
				Handler: GetInventoryHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/inventory/list",
				Handler: ListInventoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/inventory/order-log/list",
				Handler: ListOrderLogHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inventory/purchase-inbound",
				Handler: PurchaseInboundHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/inventory/record/list",
				Handler: ListInventoryRecordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inventory/sales-outbound",
				Handler: SalesOutboundHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inventory/transfer/audit",
				Handler: AuditInventoryTransferHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inventory/transfer/create",
				Handler: CreateInventoryTransferHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inventory/transfer/delete",
				Handler: DeleteInventoryTransferHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inventory/transfer/execute",
				Handler: ExecuteInventoryTransferHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/inventory/transfer/get/:id",
				Handler: GetInventoryTransferHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/inventory/transfer/list",
				Handler: ListInventoryTransferHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inventory/transfer/status",
				Handler: UpdateInventoryTransferStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inventory/transfer/update",
				Handler: UpdateInventoryTransferHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/inventory/warehouse/list",
				Handler: ListWarehouseInventoryHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/activity/list",
				Handler: ListActivityHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/logout",
				Handler: LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/refresh",
				Handler: RefreshTokenHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/assign-roles",
				Handler: AssignRolesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/create",
				Handler: CreateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/delete",
				Handler: DeleteUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/get/:id",
				Handler: GetUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/list",
				Handler: ListUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/update",
				Handler: UpdateUserHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/role/assign-menus",
				Handler: AssignMenusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/role/assign-permissions",
				Handler: AssignPermissionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/role/create",
				Handler: CreateRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/role/delete",
				Handler: DeleteRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/role/get/:id",
				Handler: GetRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/role/list",
				Handler: ListRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/role/update",
				Handler: UpdateRoleHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/supplier/active-list",
				Handler: ListActiveSupplierHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/supplier/create",
				Handler: CreateSupplierHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/supplier/delete",
				Handler: DeleteSupplierHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/supplier/get/:id",
				Handler: GetSupplierHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/supplier/list",
				Handler: ListSupplierHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/supplier/update",
				Handler: UpdateSupplierHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/customer/active-list",
				Handler: ListActiveCustomerHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/customer/create",
				Handler: CreateCustomerHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/customer/delete",
				Handler: DeleteCustomerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/customer/get/:id",
				Handler: GetCustomerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/customer/list",
				Handler: ListCustomerHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/customer/update",
				Handler: UpdateCustomerHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/purchase/order/create",
				Handler: CreatePurchaseOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/purchase/order/delete",
				Handler: DeletePurchaseOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/purchase/order/get/:id",
				Handler: GetPurchaseOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/purchase/order/inbound",
				Handler: PurchaseOrderInboundHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/purchase/order/list",
				Handler: ListPurchaseOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/purchase/order/status",
				Handler: UpdatePurchaseOrderStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/purchase/order/update",
				Handler: UpdatePurchaseOrderHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/sales/order/create",
				Handler: CreateSalesOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sales/order/delete",
				Handler: DeleteSalesOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/sales/order/get/:id",
				Handler: GetSalesOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/sales/order/list",
				Handler: ListSalesOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sales/order/status",
				Handler: UpdateSalesOrderStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sales/order/update",
				Handler: UpdateSalesOrderHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/erp/statistics/business",
				Handler: GetErpBusinessHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/erp/statistics/dashboard",
				Handler: GetErpDashboardHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/erp/statistics/inventory-alert",
				Handler: GetErpInventoryAlertHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/erp/statistics/order-status",
				Handler: GetErpOrderStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/erp/statistics/overview",
				Handler: GetErpOverviewHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/erp/statistics/todo-data",
				Handler: GetErpTodoDataHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/erp/statistics/top-products",
				Handler: GetErpTopProductsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/erp/statistics/trend",
				Handler: GetErpTrendHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/erp/init-data",
				Handler: InitDataHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/permission/create",
				Handler: CreatePermissionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/permission/delete",
				Handler: DeletePermissionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/permission/get/:id",
				Handler: GetPermissionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/permission/list",
				Handler: ListPermissionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/permission/update",
				Handler: UpdatePermissionHandler(serverCtx),
			},
		},
	)
}
