// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ActivityInfo struct {
	ID        uint   `json:"id"`
	UserID    uint   `json:"user_id"`
	Username  string `json:"username"`
	Action    string `json:"action"`
	Module    string `json:"module"`
	Content   string `json:"content"`
	URL       string `json:"url"`
	IP        string `json:"ip"`
	CreatedAt string `json:"created_at"`
}

type AdjustInventoryRequest struct {
	ProductID   uint   `json:"product_id" binding:"required"`
	WarehouseID uint   `json:"warehouse_id" binding:"required"`
	Quantity    int    `json:"quantity" binding:"required"`
	Remark      string `json:"remark"`
}

type ApproveInventoryAdjustRequest struct {
	ID     uint   `json:"id" binding:"required"`
	Status int    `json:"status" binding:"required"`
	Remark string `json:"remark"`
	Note   string `json:"note"`
}

type AssignMenuPermissionsRequest struct {
	MenuID        uint   `json:"menu_id" binding:"required"`
	PermissionIDs []uint `json:"permission_ids" binding:"required"`
}

type AssignMenusRequest struct {
	RoleID  uint   `json:"role_id" binding:"required"`
	MenuIDs []uint `json:"menu_ids" binding:"required"`
}

type AssignPermissionsRequest struct {
	RoleID        uint   `json:"role_id" binding:"required"`
	PermissionIDs []uint `json:"permission_ids" binding:"required"`
}

type AssignRolesRequest struct {
	UserID  uint   `json:"user_id" binding:"required"`
	RoleIDs []uint `json:"role_ids" binding:"required"`
}

type AuditInventoryTransferRequest struct {
	ID     uint   `json:"id" binding:"required"`
	Status int    `json:"status" binding:"required"`
	Remark string `json:"remark"`
}

type CreateCustomerRequest struct {
	Name    string `json:"name" binding:"required"`
	Code    string `json:"code" binding:"required"`
	Contact string `json:"contact"`
	Phone   string `json:"phone"`
	Email   string `json:"email"`
	Address string `json:"address"`
	Status  int    `json:"status"`
	Desc    string `json:"desc"`
}

type CreateInventoryAdjustRequest struct {
	ProductID   uint   `json:"product_id" binding:"required"`
	WarehouseID uint   `json:"warehouse_id" binding:"required"`
	Type        int    `json:"type" binding:"required"`
	Quantity    int    `json:"quantity" binding:"required"`
	Reason      string `json:"reason"`
}

type CreateInventoryCheckRequest struct {
	WarehouseID uint                 `json:"warehouse_id" binding:"required"`
	Items       []InventoryCheckItem `json:"items"`
	Remark      string               `json:"remark"`
}

type CreateInventoryTransferRequest struct {
	FromWarehouseID uint   `json:"from_warehouse_id" binding:"required"`
	ToWarehouseID   uint   `json:"to_warehouse_id" binding:"required"`
	ProductID       uint   `json:"product_id" binding:"required"`
	Quantity        int    `json:"quantity" binding:"required"`
	Remark          string `json:"remark"`
}

type CreateMenuRequest struct {
	Name      string `json:"name" binding:"required"`
	Code      string `json:"code" binding:"required"`
	Desc      string `json:"desc"`
	ParentID  uint   `json:"parent_id"`
	Path      string `json:"path" binding:"required"`
	Component string `json:"component" binding:"required"`
	Icon      string `json:"icon"`
	Sort      int    `json:"sort"`
	Status    int    `json:"status"`
}

type CreatePermissionRequest struct {
	Name   string `json:"name" binding:"required"`
	Code   string `json:"code" binding:"required"`
	Desc   string `json:"desc"`
	Path   string `json:"path"`
	Sort   int    `json:"sort"`
	Status int    `json:"status"`
	MenuID uint   `json:"menu_id"`
}

type CreateProductCategoryRequest struct {
	Name     string `json:"name" binding:"required"`
	Code     string `json:"code" binding:"required"`
	ParentID uint   `json:"parent_id"`
	Sort     int    `json:"sort"`
	Status   int    `json:"status"`
	Desc     string `json:"desc"`
}

type CreateProductRequest struct {
	Name        string  `json:"name" binding:"required"`
	Code        string  `json:"code" binding:"required"`
	Spec        string  `json:"spec"`
	CategoryID  uint    `json:"category_id"`
	CostPrice   float64 `json:"cost_price"`
	SalePrice   float64 `json:"sale_price"`
	Price       float64 `json:"price"`
	Unit        string  `json:"unit"`
	MinStock    int     `json:"min_stock"`
	MaxStock    int     `json:"max_stock"`
	SafetyStock int     `json:"safety_stock"`
	Status      int     `json:"status"`
	Desc        string  `json:"desc"`
}

type CreateProductUnitRequest struct {
	ProductID uint    `json:"product_id" binding:"required"`
	UnitName  string  `json:"unit_name"`
	Ratio     float64 `json:"ratio" binding:"required"`
	IsMain    int     `json:"is_main"`
}

type CreatePurchaseOrderItem struct {
	ProductID uint    `json:"product_id" binding:"required"`
	UnitID    uint    `json:"unit_id"`
	UnitName  string  `json:"unit_name"`
	Ratio     float64 `json:"ratio"`
	Quantity  int     `json:"quantity" binding:"required"`
	UnitPrice float64 `json:"unit_price" binding:"required"`
}

type CreatePurchaseOrderRequest struct {
	SupplierID  uint                      `json:"supplier_id" binding:"required"`
	WarehouseID uint                      `json:"warehouse_id" binding:"required"`
	Remark      string                    `json:"remark"`
	Items       []CreatePurchaseOrderItem `json:"items" binding:"required"`
}

type CreateRoleRequest struct {
	Name   string `json:"name" binding:"required"`
	Code   string `json:"code" binding:"required"`
	Desc   string `json:"desc"`
	Status int    `json:"status"`
}

type CreateSalesOrderRequest struct {
	CustomerID  uint             `json:"customer_id" binding:"required"`
	WarehouseID uint             `json:"warehouse_id" binding:"required"`
	Remark      string           `json:"remark"`
	Items       []SalesOrderItem `json:"items" binding:"required"`
}

type CreateSupplierRequest struct {
	Name    string `json:"name" binding:"required"`
	Code    string `json:"code" binding:"required"`
	Contact string `json:"contact"`
	Phone   string `json:"phone"`
	Email   string `json:"email"`
	Address string `json:"address"`
	Status  int    `json:"status"`
	Desc    string `json:"desc"`
}

type CreateUserRequest struct {
	Username string `json:"username" binding:"required"`
	Password string `json:"password" binding:"required"`
	Nickname string `json:"nickname"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Status   int    `json:"status"`
}

type CreateWarehouseRequest struct {
	Name    string `json:"name" binding:"required"`
	Code    string `json:"code" binding:"required"`
	Address string `json:"address"`
	Contact string `json:"contact"`
	Phone   string `json:"phone"`
	Status  int    `json:"status"`
	Desc    string `json:"desc"`
}

type CustomerInfo struct {
	ID        uint   `json:"id"`
	Name      string `json:"name"`
	Code      string `json:"code"`
	Contact   string `json:"contact"`
	Phone     string `json:"phone"`
	Email     string `json:"email"`
	Address   string `json:"address"`
	Status    int    `json:"status"`
	Desc      string `json:"desc"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type DeleteCustomerRequest struct {
	ID uint `json:"id" binding:"required"`
}

type DeleteInventoryCheckRequest struct {
	ID uint `json:"id" binding:"required"`
}

type DeleteInventoryTransferRequest struct {
	ID uint `json:"id" binding:"required"`
}

type DeleteMenuRequest struct {
	ID uint `json:"id" binding:"required"`
}

type DeletePermissionRequest struct {
	ID uint `json:"id" binding:"required"`
}

type DeleteProductCategoryRequest struct {
	ID uint `json:"id" binding:"required"`
}

type DeleteProductRequest struct {
	ID uint `json:"id" binding:"required"`
}

type DeleteProductUnitRequest struct {
	ID uint `json:"id" binding:"required"`
}

type DeletePurchaseOrderRequest struct {
	ID uint `json:"id" binding:"required"`
}

type DeleteRoleRequest struct {
	ID uint `json:"id" binding:"required"`
}

type DeleteSalesOrderRequest struct {
	ID uint `json:"id" binding:"required"`
}

type DeleteSupplierRequest struct {
	ID uint `json:"id" binding:"required"`
}

type DeleteUserRequest struct {
	ID uint `json:"id" binding:"required"`
}

type DeleteWarehouseRequest struct {
	ID uint `json:"id" binding:"required"`
}

type EmptyResponse struct {
}

type ErpBusinessResponse struct {
	SupplierCount        int `json:"supplier_count"`
	CustomerCount        int `json:"customer_count"`
	ActiveSupplierCount  int `json:"active_supplier_count"`
	ActiveCustomerCount  int `json:"active_customer_count"`
	ProductCount         int `json:"product_count"`
	WarehouseCount       int `json:"warehouse_count"`
	LowStockProductCount int `json:"low_stock_product_count"`
}

type ErpDashboardResponse struct {
	TotalProducts  int `json:"total_products"`
	TotalSuppliers int `json:"total_suppliers"`
	TotalCustomers int `json:"total_customers"`
	TotalOrders    int `json:"total_orders"`
}

type ErpInventoryAlertResponse struct {
	ID          uint   `json:"id"`
	ProductID   uint   `json:"product_id"`
	ProductName string `json:"product_name"`
	ProductCode string `json:"product_code"`
	WarehouseID uint   `json:"warehouse_id"`
	Warehouse   string `json:"warehouse"`
	Quantity    int    `json:"quantity"`
	MinStock    int    `json:"min_stock"`
	MaxStock    int    `json:"max_stock"`
	SafetyStock int    `json:"safety_stock"`
	AlertType   int    `json:"alert_type"`
	AlertLevel  int    `json:"alert_level"`
	CreatedAt   string `json:"created_at"`
}

type ErpOrderStatusRequest struct {
	Type string `form:"type,optional"`
}

type ErpOrderStatusResponse struct {
	Pending   int `json:"pending"`
	Approved  int `json:"approved"`
	Completed int `json:"completed"`
	Cancelled int `json:"cancelled"`
}

type ErpOverviewResponse struct {
	PurchaseAmount float64 `json:"purchase_amount"`
	SalesAmount    float64 `json:"sales_amount"`
	TotalInventory int     `json:"total_inventory"`
	TotalOrders    int     `json:"total_orders"`
	UserCount      int64   `json:"user_count"`
	ProductCount   int64   `json:"product_count"`
}

type ErpTodoData struct {
	PendingCheckOrders    int `json:"pending_check_orders"`
	PendingAdjustRequests int `json:"pending_adjust_requests"`
	PendingTransfers      int `json:"pending_transfers"`
	PendingPurchases      int `json:"pending_purchases"`
	PendingSales          int `json:"pending_sales"`
}

type ErpTodoDataResponse struct {
	PendingCheckOrders    int `json:"pending_check_orders"`
	PendingAdjustRequests int `json:"pending_adjust_requests"`
	PendingTransfers      int `json:"pending_transfers"`
	PendingPurchases      int `json:"pending_purchases"`
	PendingSales          int `json:"pending_sales"`
}

type ErpTopProductResponse struct {
	Rank        int     `json:"rank"`
	ProductName string  `json:"product_name"`
	Quantity    int     `json:"quantity"`
	Amount      float64 `json:"amount"`
}

type ErpTrendRequest struct {
	Days int `form:"days,optional"`
}

type ErpTrendResponse struct {
	Dates        []string  `json:"dates"`
	PurchaseData []float64 `json:"purchase_data"`
	SalesData    []float64 `json:"sales_data"`
}

type ExecuteInventoryTransferRequest struct {
	ID uint `json:"id" binding:"required"`
}

type GenerateAdjustFromCheckRequest struct {
	ID uint `json:"id" binding:"required"`
}

type GenerateAdjustFromCheckResponse struct {
	Success     bool   `json:"success"`
	AdjustCount int    `json:"adjust_count"`
	AdjustIds   []uint `json:"adjust_ids"`
	Message     string `json:"message"`
}

type GetCurrentStockRequest struct {
	ProductID   uint `form:"product_id"`
	WarehouseID uint `form:"warehouse_id"`
}

type GetCurrentStockResponse struct {
	ProductID   uint `json:"product_id"`
	WarehouseID uint `json:"warehouse_id"`
	Quantity    int  `json:"quantity"`
}

type GetCustomerRequest struct {
	ID uint `path:"id"`
}

type GetInventoryCheckRequest struct {
	ID uint `path:"id"`
}

type GetInventoryHistoryRequest struct {
	ProductID   uint `form:"product_id"`
	WarehouseID uint `form:"warehouse_id"`
}

type GetInventoryRequest struct {
	ID uint `path:"id"`
}

type GetInventoryTransferRequest struct {
	ID uint `path:"id"`
}

type GetMenuRequest struct {
	ID uint `path:"id"`
}

type GetPermissionRequest struct {
	ID uint `path:"id"`
}

type GetProductRequest struct {
	ID uint `path:"id"`
}

type GetProductUnitRequest struct {
	ID uint `path:"id"`
}

type GetPurchaseOrderRequest struct {
	ID uint `path:"id"`
}

type GetRoleRequest struct {
	ID uint `path:"id"`
}

type GetSalesOrderRequest struct {
	ID uint `path:"id"`
}

type GetSupplierRequest struct {
	ID uint `path:"id"`
}

type GetUserRequest struct {
	ID uint `path:"id"`
}

type GetWarehouseRequest struct {
	ID uint `path:"id"`
}

type InitDataResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type InventoryAdjustInfo struct {
	ID          uint   `json:"id"`
	ProductID   uint   `json:"product_id"`
	Product     string `json:"product"`
	WarehouseID uint   `json:"warehouse_id"`
	Warehouse   string `json:"warehouse"`
	Type        int    `json:"type"`
	TypeText    string `json:"type_text"`
	Quantity    int    `json:"quantity"`
	Remark      string `json:"remark"`
	CreatedAt   string `json:"created_at"`
}

type InventoryAdjustRequestInfo struct {
	ID          uint          `json:"id"`
	RequestNo   string        `json:"request_no"`
	ProductID   uint          `json:"product_id"`
	Product     ProductInfo   `json:"product"`
	WarehouseID uint          `json:"warehouse_id"`
	Warehouse   WarehouseInfo `json:"warehouse"`
	Type        int           `json:"type"`
	TypeText    string        `json:"type_text"`
	TypeDesc    string        `json:"type_desc"`
	Quantity    int           `json:"quantity"`
	BeforeQty   int           `json:"before_qty"`
	AfterQty    int           `json:"after_qty"`
	Status      int           `json:"status"`
	StatusText  string        `json:"status_text"`
	StatusDesc  string        `json:"status_desc"`
	Reason      string        `json:"reason"`
	Remark      string        `json:"remark"`
	ApplicantID uint          `json:"applicant_id"`
	Applicant   UserInfo      `json:"applicant"`
	ApproverID  uint          `json:"approver_id"`
	Approver    UserInfo      `json:"approver"`
	ApproveNote string        `json:"approve_note"`
	ApproveTime string        `json:"approve_time"`
	CreatedAt   string        `json:"created_at"`
}

type InventoryAlertInfo struct {
	ID          uint   `json:"id"`
	ProductID   uint   `json:"product_id"`
	Product     string `json:"product"`
	ProductName string `json:"product_name"`
	ProductCode string `json:"product_code"`
	Spec        string `json:"spec"`
	WarehouseID uint   `json:"warehouse_id"`
	Warehouse   string `json:"warehouse"`
	Quantity    int    `json:"quantity"`
	MinStock    int    `json:"min_stock"`
	MaxStock    int    `json:"max_stock"`
	SafetyStock int    `json:"safety_stock"`
	AlertLevel  int    `json:"alert_level"`
	AlertType   int    `json:"alert_type"`
	CreatedAt   string `json:"created_at"`
}

type InventoryCheckInfo struct {
	ID          uint                     `json:"id"`
	CheckNo     string                   `json:"check_no"`
	WarehouseID uint                     `json:"warehouse_id"`
	Warehouse   WarehouseInfo            `json:"warehouse"`
	TotalDiff   int                      `json:"total_diff"`
	Status      int                      `json:"status"`
	StatusText  string                   `json:"status_text"`
	Remark      string                   `json:"remark"`
	Items       []InventoryCheckItemInfo `json:"items"`
	CreatedAt   string                   `json:"created_at"`
	UpdatedAt   string                   `json:"updated_at"`
}

type InventoryCheckItem struct {
	ID        uint   `json:"id"`
	ProductID uint   `json:"product_id" binding:"required"`
	Quantity  int    `json:"quantity" binding:"required"`
	ActualQty int    `json:"actual_qty"`
	Remark    string `json:"remark"`
}

type InventoryCheckItemInfo struct {
	ID        uint        `json:"id"`
	CheckID   uint        `json:"check_id"`
	ProductID uint        `json:"product_id"`
	Product   ProductInfo `json:"product"`
	Quantity  int         `json:"quantity"`
	SystemQty int         `json:"system_qty"`
	ActualQty int         `json:"actual_qty"`
	DiffQty   int         `json:"diff_qty"`
	Status    int         `json:"status"`
	Remark    string      `json:"remark"`
}

type InventoryCheckItemUpdate struct {
	ID        uint `json:"id" binding:"required"`
	ActualQty int  `json:"actual_qty"`
}

type InventoryCheckResponse struct {
	Check InventoryCheckInfo `json:"check"`
}

type InventoryCheckResult struct {
	ID          uint   `json:"id"`
	CheckID     uint   `json:"check_id"`
	ProductID   uint   `json:"product_id"`
	Product     string `json:"product"`
	ProductCode string `json:"product_code"`
	Spec        string `json:"spec"`
	StockQty    int    `json:"stock_qty"`
	CheckQty    int    `json:"check_qty"`
	DiffQty     int    `json:"diff_qty"`
	Remark      string `json:"remark"`
}

type InventoryCheckStatusRequest struct {
	ID     uint `json:"id" binding:"required"`
	Status int  `json:"status" binding:"required"`
}

type InventoryInfo struct {
	ID             uint          `json:"id"`
	ProductID      uint          `json:"product_id"`
	Product        ProductInfo   `json:"product"`
	WarehouseID    uint          `json:"warehouse_id"`
	Warehouse      WarehouseInfo `json:"warehouse"`
	Quantity       int           `json:"quantity"`
	Type           int           `json:"type"`
	OrderType      int           `json:"order_type"`
	OrderID        uint          `json:"order_id"`
	Remark         string        `json:"remark"`
	BeforeQuantity int           `json:"before_quantity"`
	AfterQuantity  int           `json:"after_quantity"`
	CreatedAt      string        `json:"created_at"`
	UpdatedAt      string        `json:"updated_at"`
}

type InventoryRecordInfo struct {
	ID             uint   `json:"id"`
	ProductID      uint   `json:"product_id"`
	Product        string `json:"product"`
	ProductCode    string `json:"product_code"`
	Unit           string `json:"unit"`
	WarehouseID    uint   `json:"warehouse_id"`
	Warehouse      string `json:"warehouse"`
	Type           int    `json:"type"`
	TypeText       string `json:"type_text"`
	Quantity       int    `json:"quantity"`
	Balance        int    `json:"balance"`
	OrderNo        string `json:"order_no"`
	Remark         string `json:"remark"`
	CreatedAt      string `json:"created_at"`
	BeforeQuantity int    `json:"before_quantity"`
	AfterQuantity  int    `json:"after_quantity"`
}

type InventoryTransferInfo struct {
	ID              uint                        `json:"id"`
	TransferNo      string                      `json:"transfer_no"`
	FromWarehouseID uint                        `json:"from_warehouse_id"`
	FromWarehouse   WarehouseInfo               `json:"from_warehouse"`
	ToWarehouseID   uint                        `json:"to_warehouse_id"`
	ToWarehouse     WarehouseInfo               `json:"to_warehouse"`
	ProductID       uint                        `json:"product_id"`
	Product         ProductInfo                 `json:"product"`
	Quantity        int                         `json:"quantity"`
	Status          int                         `json:"status"`
	StatusText      string                      `json:"status_text"`
	Remark          string                      `json:"remark"`
	Items           []InventoryTransferItemInfo `json:"items"`
	CreatedAt       string                      `json:"created_at"`
	CreatedBy       uint                        `json:"created_by"`
	CreatedByName   string                      `json:"created_by_name"`
	AuditedBy       uint                        `json:"audited_by"`
	AuditedByName   string                      `json:"audited_by_name"`
	AuditedAt       string                      `json:"audited_at"`
	ExecutedBy      uint                        `json:"executed_by"`
	ExecutedByName  string                      `json:"executed_by_name"`
	ExecutedAt      string                      `json:"executed_at"`
	UpdatedAt       string                      `json:"updated_at"`
}

type InventoryTransferItem struct {
	ProductID uint   `json:"product_id" binding:"required"`
	Quantity  int    `json:"quantity" binding:"required"`
	Remark    string `json:"remark"`
}

type InventoryTransferItemInfo struct {
	ID          uint   `json:"id"`
	TransferID  uint   `json:"transfer_id"`
	ProductID   uint   `json:"product_id"`
	Product     string `json:"product"`
	ProductCode string `json:"product_code"`
	Spec        string `json:"spec"`
	Quantity    int    `json:"quantity"`
	Remark      string `json:"remark"`
}

type InventoryTransferRequest struct {
	FromWarehouseID uint                    `json:"from_warehouse_id" binding:"required"`
	ToWarehouseID   uint                    `json:"to_warehouse_id" binding:"required"`
	Items           []InventoryTransferItem `json:"items" binding:"required"`
	Remark          string                  `json:"remark"`
}

type InventoryTransferResponse struct {
	Transfer InventoryTransferInfo `json:"transfer"`
}

type InventoryTransferStatusRequest struct {
	ID     uint `json:"id" binding:"required"`
	Status int  `json:"status" binding:"required"`
}

type ListActivityRequest struct {
	Page      int    `form:"page,optional"`
	PageSize  int    `form:"page_size,optional"`
	UserID    uint   `form:"user_id,optional"`
	Username  string `form:"username,optional"`
	Module    string `form:"module,optional"`
	StartTime string `form:"start_time,optional"`
	EndTime   string `form:"end_time,optional"`
}

type ListActivityResponse struct {
	Activities []ActivityInfo `json:"activities"`
	Total      int64          `json:"total"`
}

type ListCustomerRequest struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"page_size,optional"`
	Name     string `form:"name,optional"`
}

type ListCustomerResponse struct {
	Customers []CustomerInfo `json:"customers"`
	Total     int64          `json:"total"`
}

type ListErpInventoryAlertRequest struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"page_size,optional"`
	Name     string `form:"name,optional"`
}

type ListErpInventoryAlertResponse struct {
	Alerts []ErpInventoryAlertResponse `json:"alerts"`
	Total  int64                       `json:"total"`
}

type ListInventoryAdjustRequest struct {
	Page        int    `form:"page,optional"`
	PageSize    int    `form:"page_size,optional"`
	ProductID   uint   `form:"product_id,optional"`
	WarehouseID uint   `form:"warehouse_id,optional"`
	Status      int    `form:"status,optional"`
	StartTime   string `form:"start_time,optional"`
	EndTime     string `form:"end_time,optional"`
}

type ListInventoryAdjustResponse struct {
	Requests []InventoryAdjustRequestInfo `json:"requests"`
	Total    int64                        `json:"total"`
}

type ListInventoryAlertRequest struct {
	Page      int `form:"page,optional"`
	PageSize  int `form:"page_size,optional"`
	AlertType int `form:"alert_type,optional"`
}

type ListInventoryAlertResponse struct {
	Code    int                  `json:"code"`
	Data    []InventoryAlertInfo `json:"data"`
	Message string               `json:"message"`
	Alerts  []InventoryAlertInfo `json:"alerts"`
	Total   int64                `json:"total"`
}

type ListInventoryCheckRequest struct {
	Page        int    `form:"page,optional"`
	PageSize    int    `form:"page_size,optional"`
	WarehouseID uint   `form:"warehouse_id,optional"`
	Status      int    `form:"status,optional"`
	CheckNo     string `form:"check_no,optional"`
	StartTime   string `form:"start_time,optional"`
	EndTime     string `form:"end_time,optional"`
}

type ListInventoryCheckResponse struct {
	Checks []InventoryCheckInfo `json:"checks"`
	Total  int64                `json:"total"`
}

type ListInventoryData struct {
	Checks []InventoryCheckInfo `json:"checks"`
	Total  int64                `json:"total"`
}

type ListInventoryRecordRequest struct {
	Page        int    `form:"page,optional"`
	PageSize    int    `form:"page_size,optional"`
	ProductID   uint   `form:"product_id,optional"`
	WarehouseID uint   `form:"warehouse_id,optional"`
	Type        int    `form:"type,optional"`
	StartTime   string `form:"start_time,optional"`
	EndTime     string `form:"end_time,optional"`
}

type ListInventoryRecordResponse struct {
	Records []InventoryRecordInfo `json:"records"`
	Total   int64                 `json:"total"`
}

type ListInventoryRequest struct {
	Page        int    `form:"page,optional"`
	PageSize    int    `form:"page_size,optional"`
	ProductID   uint   `form:"product_id,optional"`
	WarehouseID uint   `form:"warehouse_id,optional"`
	ProductName string `form:"product_name,optional"`
}

type ListInventoryResponse struct {
	Inventory []InventoryInfo `json:"inventory"`
	Total     int64           `json:"total"`
}

type ListInventoryTransferData struct {
	Transfers []InventoryTransferInfo `json:"transfers"`
	Total     int64                   `json:"total"`
}

type ListInventoryTransferRequest struct {
	Page            int    `form:"page,optional"`
	PageSize        int    `form:"page_size,optional"`
	TransferNo      string `form:"transfer_no,optional"`
	FromWarehouseID int    `form:"from_warehouse_id,optional"`
	ToWarehouseID   int    `form:"to_warehouse_id,optional"`
	ProductID       int    `form:"product_id,optional"`
	Status          int    `form:"status,optional"`
	StartTime       string `form:"start_time,optional"`
	EndTime         string `form:"end_time,optional"`
}

type ListInventoryTransferResponse struct {
	Transfers []InventoryTransferInfo `json:"transfers"`
	Total     int64                   `json:"total"`
}

type ListMenuRequest struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"page_size,optional"`
	Name     string `form:"name,optional"`
}

type ListMenuResponse struct {
	Menus []MenuInfo `json:"menus"`
	Total int64      `json:"total"`
}

type ListOrderLogRequest struct {
	OrderID    uint   `form:"order_id,optional"`
	OrderType  int    `form:"order_type,optional"`
	OperatorID uint   `form:"operator_id,optional"`
	StartTime  string `form:"start_time,optional"`
	EndTime    string `form:"end_time,optional"`
}

type ListOrderLogResponse struct {
	Logs  []OrderLogInfo `json:"logs"`
	Total int64          `json:"total"`
}

type ListPermissionRequest struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"page_size,optional"`
	Name     string `form:"name,optional"`
}

type ListPermissionResponse struct {
	Permissions []PermissionInfo `json:"permissions"`
	Total       int64            `json:"total"`
}

type ListProductCategoryRequest struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"page_size,optional"`
	Name     string `form:"name,optional"`
}

type ListProductCategoryResponse struct {
	Categories []ProductCategoryInfo `json:"categories"`
	Total      int64                 `json:"total"`
}

type ListProductRequest struct {
	Page       int    `form:"page,optional"`
	PageSize   int    `form:"page_size,optional"`
	Name       string `form:"name,optional"`
	Code       string `form:"code,optional"`
	CategoryID uint   `form:"category_id,optional"`
}

type ListProductResponse struct {
	Products []ProductInfo `json:"products"`
	Total    int64         `json:"total"`
}

type ListProductUnitRequest struct {
	Page        int    `form:"page,optional"`
	PageSize    int    `form:"page_size,optional"`
	ProductID   uint   `form:"product_id,optional"`
	ProductName string `form:"product_name,optional"`
}

type ListProductUnitResponse struct {
	Units []ProductUnitInfo `json:"units"`
	Total int64             `json:"total"`
}

type ListPurchaseOrderRequest struct {
	Page       int    `form:"page,optional"`
	PageSize   int    `form:"page_size,optional"`
	OrderNo    string `form:"order_no,optional"`
	SupplierID uint   `form:"supplier_id,optional"`
	Status     int    `form:"status,optional"`
	StartTime  string `form:"start_time,optional"`
	EndTime    string `form:"end_time,optional"`
}

type ListPurchaseOrderResponse struct {
	Orders []PurchaseOrderInfo `json:"orders"`
	Total  int64               `json:"total"`
}

type ListRoleRequest struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"page_size,optional"`
	Name     string `form:"name,optional"`
}

type ListRoleResponse struct {
	Roles []RoleInfo `json:"roles"`
	Total int64      `json:"total"`
}

type ListSalesOrderRequest struct {
	Page       int    `form:"page,optional"`
	PageSize   int    `form:"page_size,optional"`
	OrderNo    string `form:"order_no,optional"`
	CustomerID uint   `form:"customer_id,optional"`
	Status     int    `form:"status,optional"`
	StartTime  string `form:"start_time,optional"`
	EndTime    string `form:"end_time,optional"`
}

type ListSalesOrderResponse struct {
	Orders []SalesOrderInfo `json:"orders"`
	Total  int64            `json:"total"`
}

type ListSupplierRequest struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"page_size,optional"`
	Name     string `form:"name,optional"`
}

type ListSupplierResponse struct {
	Suppliers []SupplierInfo `json:"suppliers"`
	Total     int64          `json:"total"`
}

type ListUserRequest struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"page_size,optional"`
	Username string `form:"username,optional"`
}

type ListUserResponse struct {
	Users []UserInfo `json:"users"`
	Total int64      `json:"total"`
}

type ListWarehouseInventoryRequest struct {
	Page        int  `form:"page,optional"`
	PageSize    int  `form:"page_size,optional"`
	ProductID   uint `form:"product_id,optional"`
	WarehouseID uint `form:"warehouse_id,optional"`
}

type ListWarehouseInventoryResponse struct {
	Inventories []WarehouseInventoryInfo `json:"inventories"`
	Total       int64                    `json:"total"`
}

type ListWarehouseRequest struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"page_size,optional"`
	Name     string `form:"name,optional"`
}

type ListWarehouseResponse struct {
	Warehouses []WarehouseInfo `json:"warehouses"`
	Total      int64           `json:"total"`
}

type LoginRequest struct {
	Username string `json:"username" binding:"required"`
	Password string `json:"password" binding:"required"`
}

type LoginResponse struct {
	Token string   `json:"token"`
	User  UserInfo `json:"user"`
}

type LogoutRequest struct {
}

type LogoutResponse struct {
	Success bool `json:"success"`
}

type MenuInfo struct {
	ID          uint             `json:"id"`
	Name        string           `json:"name"`
	Code        string           `json:"code"`
	Desc        string           `json:"desc"`
	ParentID    uint             `json:"parent_id"`
	Path        string           `json:"path"`
	Component   string           `json:"component"`
	Icon        string           `json:"icon"`
	Sort        int              `json:"sort"`
	Status      int              `json:"status"`
	Permissions []PermissionInfo `json:"permissions"`
	Children    []MenuInfo       `json:"children"`
}

type OrderLogInfo struct {
	ID               uint   `json:"id"`
	OrderID          uint   `json:"order_id"`
	OrderType        int    `json:"order_type"`
	OrderTypeDesc    string `json:"order_type_desc"`
	BeforeStatus     int    `json:"before_status"`
	BeforeStatusDesc string `json:"before_status_desc"`
	AfterStatus      int    `json:"after_status"`
	AfterStatusDesc  string `json:"after_status_desc"`
	OperatorID       uint   `json:"operator_id"`
	OperatorName     string `json:"operator_name"`
	Remark           string `json:"remark"`
	CreatedAt        string `json:"created_at"`
}

type PermissionInfo struct {
	ID       uint   `json:"id"`
	Name     string `json:"name"`
	Code     string `json:"code"`
	Desc     string `json:"desc"`
	Type     int    `json:"type"`
	ParentID uint   `json:"parent_id"`
	MenuID   uint   `json:"menu_id"`
	Path     string `json:"path"`
	Sort     int    `json:"sort"`
	Status   int    `json:"status"`
}

type ProductCategoryInfo struct {
	ID        uint                  `json:"id"`
	Name      string                `json:"name"`
	Code      string                `json:"code"`
	ParentID  uint                  `json:"parent_id"`
	Sort      int                   `json:"sort"`
	Status    int                   `json:"status"`
	Desc      string                `json:"desc"`
	Children  []ProductCategoryInfo `json:"children"`
	CreatedAt string                `json:"created_at"`
	UpdatedAt string                `json:"updated_at"`
}

type ProductInfo struct {
	ID          uint                `json:"id"`
	Name        string              `json:"name"`
	Code        string              `json:"code"`
	Spec        string              `json:"spec"`
	CategoryID  uint                `json:"category_id"`
	Unit        string              `json:"unit"`
	MinStock    int                 `json:"min_stock"`
	MaxStock    int                 `json:"max_stock"`
	SafetyStock int                 `json:"safety_stock"`
	CostPrice   float64             `json:"cost_price"`
	SalePrice   float64             `json:"sale_price"`
	Price       float64             `json:"price"`
	Status      int                 `json:"status"`
	Desc        string              `json:"desc"`
	Stock       int                 `json:"stock"`
	MainUnit    string              `json:"main_unit"`
	Units       []ProductUnitInfo   `json:"units"`
	Category    ProductCategoryInfo `json:"category"`
	CreatedAt   string              `json:"created_at"`
	UpdatedAt   string              `json:"updated_at"`
}

type ProductUnit struct {
	ID        uint    `json:"id"`
	ProductID uint    `json:"product_id"`
	Name      string  `json:"name"`
	UnitName  string  `json:"unit_name"`
	Ratio     float64 `json:"ratio"`
	IsMain    int     `json:"is_main"`
	Status    int     `json:"status"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
}

type ProductUnitInfo struct {
	ID          uint    `json:"id"`
	ProductID   uint    `json:"product_id"`
	ProductName string  `json:"product_name"`
	UnitName    string  `json:"unit_name"`
	Ratio       float64 `json:"ratio"`
	IsMain      int     `json:"is_main"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
}

type ProductUnitRequest struct {
	ProductID uint    `json:"product_id" binding:"required"`
	Name      string  `json:"name" binding:"required"`
	Ratio     float64 `json:"ratio" binding:"required"`
	IsMain    int     `json:"is_main"`
	Status    int     `json:"status"`
}

type PurchaseInboundRequest struct {
	OrderID     uint `json:"order_id" binding:"required"`
	WarehouseID uint `json:"warehouse_id"`
}

type PurchaseOrderInfo struct {
	ID          uint                    `json:"id"`
	OrderNo     string                  `json:"order_no"`
	SupplierID  uint                    `json:"supplier_id"`
	Supplier    SupplierInfo            `json:"supplier"`
	WarehouseID uint                    `json:"warehouse_id"`
	Warehouse   WarehouseInfo           `json:"warehouse"`
	TotalAmount float64                 `json:"total_amount"`
	Status      int                     `json:"status"`
	StatusText  string                  `json:"status_text"`
	Remark      string                  `json:"remark"`
	Items       []PurchaseOrderItemInfo `json:"items"`
	CreatedAt   string                  `json:"created_at"`
	UpdatedAt   string                  `json:"updated_at"`
}

type PurchaseOrderItem struct {
	ID          uint        `json:"id"`
	OrderID     uint        `json:"order_id"`
	ProductID   uint        `json:"product_id"`
	Product     ProductInfo `json:"product"`
	ProductCode string      `json:"product_code"`
	Spec        string      `json:"spec"`
	UnitID      uint        `json:"unit_id"`
	UnitName    string      `json:"unit_name"`
	Ratio       float64     `json:"ratio"`
	BaseQty     int         `json:"base_qty"`
	Quantity    int         `json:"quantity"`
	Price       float64     `json:"price"`
	UnitPrice   float64     `json:"unit_price"`
	Amount      float64     `json:"amount"`
}

type PurchaseOrderItemInfo struct {
	ID        uint        `json:"id"`
	OrderID   uint        `json:"order_id"`
	ProductID uint        `json:"product_id"`
	Product   ProductInfo `json:"product"`
	UnitID    uint        `json:"unit_id"`
	UnitName  string      `json:"unit_name"`
	Ratio     int         `json:"ratio"`
	Quantity  int         `json:"quantity"`
	BaseQty   int         `json:"base_qty"`
	Price     float64     `json:"price"`
	UnitPrice float64     `json:"unit_price"`
	Amount    float64     `json:"amount"`
}

type PurchaseOrderStatusRequest struct {
	ID     uint `json:"id" binding:"required"`
	Status int  `json:"status" binding:"required"`
}

type RefreshTokenRequest struct {
	Token string `json:"token" binding:"required"`
}

type RefreshTokenResponse struct {
	Token string `json:"token"`
}

type RejectInventoryAdjustRequest struct {
	ID     uint   `json:"id" binding:"required"`
	Remark string `json:"remark"`
	Note   string `json:"note"`
}

type RoleInfo struct {
	ID          uint             `json:"id"`
	Name        string           `json:"name"`
	Code        string           `json:"code"`
	Desc        string           `json:"desc"`
	Status      int              `json:"status"`
	Permissions []PermissionInfo `json:"permissions"`
	Menus       []MenuInfo       `json:"menus"`
}

type SalesOrderInfo struct {
	ID          uint                 `json:"id"`
	OrderNo     string               `json:"order_no"`
	CustomerID  uint                 `json:"customer_id"`
	Customer    CustomerInfo         `json:"customer"`
	WarehouseID uint                 `json:"warehouse_id"`
	Warehouse   WarehouseInfo        `json:"warehouse"`
	TotalAmount float64              `json:"total_amount"`
	Status      int                  `json:"status"`
	StatusText  string               `json:"status_text"`
	Remark      string               `json:"remark"`
	Items       []SalesOrderItemInfo `json:"items"`
	CreatedAt   string               `json:"created_at"`
	UpdatedAt   string               `json:"updated_at"`
}

type SalesOrderItem struct {
	ID          uint        `json:"id"`
	OrderID     uint        `json:"order_id"`
	ProductID   uint        `json:"product_id"`
	Product     ProductInfo `json:"product"`
	ProductCode string      `json:"product_code"`
	Spec        string      `json:"spec"`
	UnitID      uint        `json:"unit_id"`
	UnitName    string      `json:"unit_name"`
	Ratio       float64     `json:"ratio"`
	BaseQty     int         `json:"base_qty"`
	Quantity    int         `json:"quantity"`
	Price       float64     `json:"price"`
	UnitPrice   float64     `json:"unit_price"`
	Amount      float64     `json:"amount"`
}

type SalesOrderItemInfo struct {
	ID        uint        `json:"id"`
	OrderID   uint        `json:"order_id"`
	ProductID uint        `json:"product_id"`
	Product   ProductInfo `json:"product"`
	UnitID    uint        `json:"unit_id"`
	UnitName  string      `json:"unit_name"`
	Ratio     int         `json:"ratio"`
	Quantity  int         `json:"quantity"`
	BaseQty   int         `json:"base_qty"`
	Price     float64     `json:"price"`
	UnitPrice float64     `json:"unit_price"`
	Amount    float64     `json:"amount"`
}

type SalesOrderStatusRequest struct {
	ID     uint `json:"id" binding:"required"`
	Status int  `json:"status" binding:"required"`
}

type SalesOutboundRequest struct {
	OrderID     uint `json:"order_id" binding:"required"`
	WarehouseID uint `json:"warehouse_id" binding:"required"`
}

type SubmitInventoryCheckRequest struct {
	ID     uint   `json:"id" binding:"required"`
	Remark string `json:"remark"`
}

type SupplierInfo struct {
	ID        uint   `json:"id"`
	Name      string `json:"name"`
	Code      string `json:"code"`
	Contact   string `json:"contact"`
	Phone     string `json:"phone"`
	Email     string `json:"email"`
	Address   string `json:"address"`
	Status    int    `json:"status"`
	Desc      string `json:"desc"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type UpdateCustomerRequest struct {
	ID      uint   `json:"id" binding:"required"`
	Name    string `json:"name"`
	Code    string `json:"code"`
	Contact string `json:"contact"`
	Phone   string `json:"phone"`
	Email   string `json:"email"`
	Address string `json:"address"`
	Status  int    `json:"status"`
	Desc    string `json:"desc"`
}

type UpdateInventoryCheckRequest struct {
	ID     uint                       `json:"id" binding:"required"`
	Items  []InventoryCheckItemUpdate `json:"items"`
	Remark string                     `json:"remark"`
}

type UpdateInventoryTransferRequest struct {
	ID              uint   `json:"id" binding:"required"`
	FromWarehouseID uint   `json:"from_warehouse_id"`
	ToWarehouseID   uint   `json:"to_warehouse_id"`
	ProductID       uint   `json:"product_id"`
	Quantity        int    `json:"quantity"`
	Remark          string `json:"remark"`
}

type UpdateMenuRequest struct {
	ID        uint   `json:"id" binding:"required"`
	Name      string `json:"name"`
	Code      string `json:"code"`
	Desc      string `json:"desc"`
	ParentID  uint   `json:"parent_id"`
	Path      string `json:"path"`
	Component string `json:"component"`
	Icon      string `json:"icon"`
	Sort      int    `json:"sort"`
	Status    int    `json:"status"`
}

type UpdatePermissionRequest struct {
	ID     uint   `json:"id" binding:"required"`
	Name   string `json:"name"`
	Code   string `json:"code"`
	Desc   string `json:"desc"`
	Path   string `json:"path"`
	Sort   int    `json:"sort"`
	Status int    `json:"status"`
	MenuID uint   `json:"menu_id"`
}

type UpdateProductCategoryRequest struct {
	ID       uint   `json:"id" binding:"required"`
	Name     string `json:"name"`
	Code     string `json:"code"`
	ParentID uint   `json:"parent_id"`
	Sort     int    `json:"sort"`
	Status   int    `json:"status"`
	Desc     string `json:"desc"`
}

type UpdateProductRequest struct {
	ID          uint    `json:"id" binding:"required"`
	Name        string  `json:"name"`
	Code        string  `json:"code"`
	Spec        string  `json:"spec"`
	CategoryID  uint    `json:"category_id"`
	CostPrice   float64 `json:"cost_price"`
	SalePrice   float64 `json:"sale_price"`
	Price       float64 `json:"price"`
	MinStock    int     `json:"min_stock"`
	MaxStock    int     `json:"max_stock"`
	SafetyStock int     `json:"safety_stock"`
	Status      int     `json:"status"`
	Desc        string  `json:"desc"`
}

type UpdateProductUnitRequest struct {
	ID       uint    `json:"id" binding:"required"`
	UnitName string  `json:"unit_name"`
	Ratio    float64 `json:"ratio"`
	IsMain   int     `json:"is_main"`
}

type UpdatePurchaseOrderRequest struct {
	ID          uint                `json:"id" binding:"required"`
	SupplierID  uint                `json:"supplier_id"`
	WarehouseID uint                `json:"warehouse_id"`
	Status      int                 `json:"status"`
	Remark      string              `json:"remark"`
	Items       []PurchaseOrderItem `json:"items"`
}

type UpdateRoleRequest struct {
	ID     uint   `json:"id" binding:"required"`
	Name   string `json:"name"`
	Code   string `json:"code"`
	Desc   string `json:"desc"`
	Status int    `json:"status"`
}

type UpdateSalesOrderRequest struct {
	ID          uint             `json:"id" binding:"required"`
	CustomerID  uint             `json:"customer_id"`
	WarehouseID uint             `json:"warehouse_id"`
	Status      int              `json:"status"`
	Remark      string           `json:"remark"`
	Items       []SalesOrderItem `json:"items"`
}

type UpdateSupplierRequest struct {
	ID      uint   `json:"id" binding:"required"`
	Name    string `json:"name"`
	Code    string `json:"code"`
	Contact string `json:"contact"`
	Phone   string `json:"phone"`
	Email   string `json:"email"`
	Address string `json:"address"`
	Status  int    `json:"status"`
	Desc    string `json:"desc"`
}

type UpdateUserRequest struct {
	ID       uint   `json:"id" binding:"required"`
	Username string `json:"username"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Status   int    `json:"status"`
}

type UpdateWarehouseRequest struct {
	ID      uint   `json:"id" binding:"required"`
	Name    string `json:"name"`
	Code    string `json:"code"`
	Address string `json:"address"`
	Contact string `json:"contact"`
	Phone   string `json:"phone"`
	Status  int    `json:"status"`
	Desc    string `json:"desc"`
}

type UserInfo struct {
	ID       uint       `json:"id"`
	Username string     `json:"username"`
	Nickname string     `json:"nickname"`
	Email    string     `json:"email"`
	Phone    string     `json:"phone"`
	Status   int        `json:"status"`
	Roles    []RoleInfo `json:"roles"`
}

type WarehouseInfo struct {
	ID        uint   `json:"id"`
	Name      string `json:"name"`
	Code      string `json:"code"`
	Address   string `json:"address"`
	Contact   string `json:"contact"`
	Phone     string `json:"phone"`
	Status    int    `json:"status"`
	Desc      string `json:"desc"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type WarehouseInventoryInfo struct {
	ID          uint   `json:"id"`
	ProductID   uint   `json:"product_id"`
	Product     string `json:"product"`
	ProductCode string `json:"product_code"`
	Spec        string `json:"spec"`
	WarehouseID uint   `json:"warehouse_id"`
	Warehouse   string `json:"warehouse"`
	Quantity    int    `json:"quantity"`
	UpdatedAt   string `json:"updated_at"`
}
